---
################################################################################
# Bio-DAMNED - Bio-Data Ansible MaNagED                                        #
#                                                                              #
# Authors: Bertrand Néron                                                      #
# Copyright © 2016  Institut Pasteur (Paris).                                  #
#                                                                              #
# Bio-DAMNED is distributed under the terms of the GNU General Public License  #
# (GPLv3). See the LICENSE file for details.                                   #
################################################################################

- include: common_tasks/setup_general_bank_tree.yml

- include: common_tasks/setup_specific_bank_tree.yml

- include: common_tasks/get_data.yml

- name: Creating blast2 directory for "{{ bank_name }}"
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ bank_root }}/{{ bank_name }}/blast2
        state=directory
        owner={{ bank_user }}
        group={{ bank_group }}
        mode=0775

- name: Cleaning "{{ bank_name }}" blast2 indexes links
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{bank_root}}/index/blast2/{{ bank_name | basename }} state=absent
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/*"

- name: Cleaning "{{ bank_name }}" blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ item }} state=absent
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/*"

- name: Copying and renaming "{{ bank_name }}" blast indexes in right directory
  become: yes
  become_user: "{{ bank_user }}"
  copy:
    src={{ item }}
    dest={{ bank_root }}/{{ bank_name }}/blast2/{{ bank_name }}{{ item | splitext | last }}
    remote_src=True
    owner={{ bank_user }}
    group={{ bank_group }}
    mode=0644
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/uncompressed/*.n*"

- name: Creating links to blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{ item }}
    dest={{bank_root}}/index/blast2/{{ item | basename }}
    state=link
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/{{ bank_name }}.*"
