---

- include: common_tasks/setup_general_bank_tree.yml

- include: common_tasks/setup_specific_bank_tree.yml

- include: common_tasks/get_data.yml

- name: Creating blast2 directory for "{{ bank_name }}"
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ bank_root }}/{{ bank_name }}/blast2
        state=directory
        owner={{ bank_user }}
        group={{ bank_group }}
        mode=0775


- name: Cleaning "{{ bank_name }}" blast2 indexes links
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{bank_root}}/index/blast2/{{ bank_name | basename }} state=absent
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/*"

- name: Cleaning "{{ bank_name }}" blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ item }} state=absent
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/*"


- name: Moving and renaming "{{ bank_name }}" blast indexes in right directory
  become: yes
  become_user: "{{ bank_user }}"
  command: mv {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa{{ item | splitext | last }} {{ bank_root }}/{{ bank_name }}/blast2/{{ bank_name }}{{ item | splitext | last }}
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa.*"

- name: Creating links to blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{ item }}
    dest={{bank_root}}/index/blast2/{{ bank_name }}{{ item | splitext | last }}
    state=link
  with_fileglob:
    - "{{ bank_root }}/{{ bank_name }}/blast2/{{ bank_name }}.*"
