---
- name: Download and index banks
  hosts: banks
  remote_user: root

  roles:
    - {role: setup_bank_tree, tags: ['setup']}
    - {role: m_tuberculosis_CDC1551, tags: ['cdc1551'], bank_name: m_tuberculosis_CDC1551}