---
- name: Download and index banks
  hosts: banks
  remote_user: root

  roles:
    - {role: setup_bank_tree, tags: ['setup']}
    - {role: genbank_genome, tags: ['cdc1551'],
       bank_name: m_tuberculosis_CDC1551,
       bank_src: "ftp://ftp.ncbi.nih.gov/genomes/archive/old_genbank/Bacteria/Mycobacterium_tuberculosis_CDC1551_uid223/AE000516.gbk"}
    - {role: fasta_genome, tags: ['yersinia_nuc'],
       bank_name: yersinia_pestis_nuc,
       bank_src: "ftp://ftp.ncbi.nih.gov/genomes/refseq/bacteria/Yersinia_pestis/reference/GCF_000009065.1_ASM906v1/GCF_000009065.1_ASM906v1_genomic.fna.gz"}
    - {role: fasta_bank, tags: ['silva_SSU_Nr99'],
       bank_name: silva_SSU,
       bank_src: "https://www.arb-silva.de/fileadmin/silva_databases/release_123_1/Exports/SILVA_123.1_SSURef_Nr99_tax_silva.fasta.gz"}
    - {role: fasta_bank, tags: ['silva_LSU_tax'],
       bank_name: silva_LSU,
       bank_src: "https://www.arb-silva.de/fileadmin/silva_databases/release_123_1/Exports/SILVA_123.1_LSURef_tax_silva.fasta.gz"}
    - {role: fasta_bank, tags: ['ncbi_16s'],
       bank_name: ncbi_16s,
       bank_src: "ftp://ftp.ncbi.nih.gov/blast/db/16SMicrobial.tar.gz"}