---
- include: common_tasks/setup_general_bank_tree.yml

- include: common_tasks/setup_specific_bank_tree.yml

- include: common_tasks/get_data.yml ext=gbk

- name: reformating "{{ bank_name }}" in fasta format
  become: yes
  become_user: "{{ bank_user }}"
  shell: squizz -c FASTA -f GENBANK {{ bank_root }}/{{ bank_name }}/uncompressed/{{ bank_name }}.gbk >> {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa

- include: common_tasks/link_fasta.yml

- include: common_tasks/golden_indexing.yml

- include: common_tasks/blast2_indexing.yml

