---
################################################################################
# Bio-DAMNED - Bio-Data Ansible MaNagED                                        #
#                                                                              #
# Authors: Bertrand Néron                                                      #
# Copyright © 2016  Institut Pasteur (Paris).                                  #
#                                                                              #
# Bio-DAMNED is distributed under the terms of the GNU General Public License  #
# (GPLv3). See the LICENSE file for details.                                   #
################################################################################

- include: common_tasks/setup_general_bank_tree.yml

- include: common_tasks/setup_specific_bank_tree.yml

- include: common_tasks/get_data.yml ext=gbk

- name: reformating "{{ bank_name }}" in fasta format
  become: yes
  become_user: "{{ bank_user }}"
  shell: squizz -c FASTA -f GENBANK {{ bank_root }}/{{ bank_name }}/uncompressed/{{ bank_name }}.gbk >> {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa

- include: common_tasks/link_fasta.yml

- set_fact: golden="{{ indexers | selectattr('tool', 'equalto', 'golden')|list}}"

- name: Start golden indexing
  include: common_tasks/golden_indexing.yml
  with_items: "{{ golden[0].vers }}"
  loop_control:
    loop_var: golden_vers

- set_fact: blast2="{{ indexers | selectattr('tool', 'equalto', 'blast2')|list}}"

- name: Start blast2 indexing
  include: common_tasks/blast2_indexing.yml
  with_items: "{{ blast2[0].vers }}"
  loop_control:
    loop_var: blast2_vers

- set_fact: blast+="{{ indexers | selectattr('tool', 'equalto', 'blast+')|list}}"

- name: Start blast+ indexing
  include: common_tasks/blast+_indexing.yml
  with_items: "{{ blast+[0].vers }}"
  loop_control:
    loop_var: blast+_vers