---

- name: creating bank "{{ bank_name }}" directory
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ bank_root }}/{{ bank_name }} state=directory owner={{ bank_user }} group={{ bank_group }} mode=0775

- name: creating bank "{{ bank_name }}" subtree directories
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{ bank_root }}/{{ bank_name }}/{{ item }} state=directory  owner={{ bank_user }} group={{ bank_group }} mode=0775
  with_items:
    - uncompressed
    - fasta
    - golden
    - blast2

- name: downloading "{{ bank_name }}"
  become: yes
  become_user: "{{ bank_user }}"
  # because of bug https://github.com/ansible/ansible-modules-core/issues/3661
  # on ansible version 2.0.2.0 we cannot use get_url : workaround use command
  #  get_url: ftp://ftp.ncbi.nih.gov/genomes/archive/old_genbank/Bacteria/Mycobacterium_tuberculosis_CDC1551_uid223/AE000516.gbk
  #curl ftp://ftp.ncbi.nih.gov/genomes/archive/old_genbank/Bacteria/Mycobacterium_tuberculosis_CDC1551_uid223/AE000516.gbk -o {{bank_name}}.gbk
  command: >
    curl {{ bank_src }} -o {{ bank_root }}/distbanks/{{ bank_src|basename }}
    creates={{ bank_root }}/distbanks/{{ bank_src|basename }}

- name: gess mime
  become: yes
  become_user: "{{ bank_user }}"
  stat: path={{ bank_root }}/distbanks/{{ bank_src|basename }} mime=True
  register: mime

- block:

  - block:
    - name: uncompressing {{ bank_name }}
      become: yes
      become_user: "{{ bank_user }}"
      unarchive: src={{ bank_root }}/distbanks/{{ bank_src|basename }} dest={{ bank_root }}/{{ bank_name }}/uncompressed/

    - name: guessing the name of uncompressed bank
      become: yes
      become_user: "{{ bank_user }}"
      find: paths={{ bank_root }}/{{ bank_name }}/uncompressed/ file_type=file
      register: uncompressed_bank

    - name: renaming {{ bank_name }}
      become: yes
      become_user: "{{ bank_user }}"
      shell: mv {{ uncompressed_bank.files[0].path }} {{ bank_root }}/{{ bank_name }}/uncompressed/{{ bank_name }}.fa

    rescue:
      - name: uncompressing gzip {{ bank_name }}
        become: yes
        become_user: "{{ bank_user }}"
        shell: >
          gunzip -c {{ bank_root }}/distbanks/{{ bank_src|basename }} > {{ bank_root }}/{{ bank_name }}/uncompressed/{{ bank_name }}.fa

  when: mime.stat.mime_type in ["application/x-gzip", "application/zip"]

- name: copy "{{ bank_name }}" in bank directory
  become: yes
  become_user: "{{ bank_user }}"
  when: mime.stat.mime_type not in ["application/x-gzip", "application/zip"]
  copy: >
    src={{ bank_root }}/distbanks/{{ bank_src|basename }}
    dest={{ bank_root }}/{{ bank_name }}/uncompressed/{{ bank_name | splitext | last }}.fa
    remote_src=True
    owner={{ bank_user }}
    group={{ bank_group }}
    mode=0644

- name: reformating "{{ bank_name }}" in fasta format
  become: yes
  become_user: "{{ bank_user }}"
  shell: >
    squizz -c FASTA -f FASTA {{ bank_name }}.fa >> {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa
    chdir={{ bank_root }}/{{ bank_name }}/uncompressed

- name: running squizz on "{{ bank_name }}"  to check format
  become: yes
  become_user: "{{ bank_user }}"
  shell: squizz {{ bank_name }}.fa chdir={{ bank_root }}/{{ bank_name }}/fasta
  register: format

- name: Checking fasta format
  fail: msg="{{ bank_name }}" not correctly formated "{{ format.stderr }}"
  when: not 'FASTA' in format.stderr

- name: creating links to fasta format
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{bank_root}}/{{ bank_name }}/fasta/{{ bank_name }}.fa
    dest={{bank_root}}/fasta/{{bank_name}}.fa
    state=link

- name: cleaning "{{ bank_name }}" blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: path={{bank_root}}/{{bank_name}}/blast2/{{ bank_name }}}.{{ item }} state=absent
  with_items:
    - nhr
    - nin
    - nsq

- name: creating blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  #formatdb  -t "{{ bank_name }}" -p F -n "{{ bank_name }}" -i {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa -l /dev/null
  shell: >
    makeblastdb -title {{ bank_name }} -in {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa -dbtype nucl
    chdir={{ bank_root }}/{{ bank_name }}/blast2

- name: moving and renaming "{{ bank_name }}" blast indexes in right directory
  become: yes
  become_user: "{{ bank_user }}"
  command: mv {{ bank_root }}/{{ bank_name }}/fasta/{{ bank_name }}.fa.{{ item }} {{ bank_root }}/{{ bank_name }}/blast2/{{ bank_name }}.{{ item }}
  with_items:
    - nhr
    - nin
    - nsq

- name: creating links to blast2 indexes
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{bank_root}}/{{ bank_name }}/blast2/{{ bank_name }}.{{ item }}
    dest={{bank_root}}/index/blast2/{{ bank_name }}.{{ item }}
    state=link
  with_items:
    - nhr
    - nin
    - nsq

- name: creating link for fasta
  become: yes
  become_user: "{{ bank_user }}"
  file: >
    src={{bank_root}}/{{ bank_name }}/fasta/{{ bank_name }}.fa
    dest={{bank_root}}/fasta/{{ bank_name }}.fa
    state=link
