---
################################################################################
# Bio-DAMNED - Bio-Data Ansible MaNagED                                        #
#                                                                              #
# Authors: Bertrand Néron                                                      #
# Copyright © 2016  Institut Pasteur (Paris).                                  #
#                                                                              #
# Bio-DAMNED is distributed under the terms of the GNU General Public License  #
# (GPLv3). See the LICENSE file for details.                                   #
################################################################################

- include: common_tasks/setup_general_bank_tree.yml

- include: common_tasks/setup_specific_bank_tree.yml

- include: common_tasks/get_data.yml ext=fa